//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fortnox.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Xmls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xmls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fortnox.UnitTest.Xmls", typeof(Xmls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Article url=&quot;https://api.fortnox.se/3/articles/1&quot;&gt;
        ///  &lt;ArticleNumber&gt;1&lt;/ArticleNumber&gt;
        ///  &lt;Bulky&gt;false&lt;/Bulky&gt;
        ///  &lt;ConstructionAccount&gt;0&lt;/ConstructionAccount&gt;
        ///  &lt;Depth&gt;&lt;/Depth&gt;
        ///  &lt;Description&gt;Fortnox Bokföring&lt;/Description&gt;
        ///  &lt;DisposableQuantity&gt;144&lt;/DisposableQuantity&gt;
        ///  &lt;EAN&gt;125544&lt;/EAN&gt;
        ///  &lt;EUAccount&gt;3018&lt;/EUAccount&gt;
        ///  &lt;EUVATAccount&gt;3016&lt;/EUVATAccount&gt;
        ///  &lt;ExportAccount&gt;3015&lt;/ExportAccount&gt;
        ///  &lt;Height&gt;&lt;/Height&gt;
        ///  &lt;Housework&gt;false&lt;/Housework&gt;
        ///  &lt;Manufacturer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Article1 {
            get {
                return ResourceManager.GetString("Article1", resourceCulture);
            }
        }
    }
}
